/* eslint-disable */
export enum CharacterTypes {
  SAVE_SELECTED_CHARACTER = '@character/SAVE_SELECTED_CHARACTER',
  EDIT_SELECTED_CHARACTER_NAME = '@character/EDIT_SELECTED_CHARACTER_NAME',
  EDIT_SELECTED_CHARACTER_DESCRIPTION = '@character/EDIT_SELECTED_CHARACTER_DESCRIPTION',
  EDIT_SELECTED_CHARACTER_SERIE_DESCRIPTION = '@character/EDIT_SELECTED_CHARACTER_SERIE_DESCRIPTION',
}
